train:
  dataset_path: /hsuraid/luotingzhuang/projects/pseudotime2/numpy_data
  csv_paths:
  - /path/to/dataset_a.csv
  - /path/to/dataset_b.csv
  csv_file_column: files
  csv_cohort_column: cohort
  input_format: numpy
  data_min_axis_size: 63
  random_crop_size: 64

crops:
  global_crops_size: 64
  local_crops_size: 32
  global_crops_in_slice_scale:
  - 0.8
  - 1.0
  global_crops_cross_slice_scale:
  - 0.8
  - 1.0
  local_crops_in_slice_scale:
  - 0.4
  - 0.8
  local_crops_cross_slice_scale:
  - 0.4
  - 0.8
